#ifndef ANALYZATOR_DEFS_H
#define ANALYZATOR_DEFS_H
#include "iostream"
#include <fstream>
#include <cstring>
#define MAX_TEXT_SIZE 10000
#define MAX_LEXEME_SIZE 100
#define MAX_KEYWORDS 11
using namespace std;
typedef char Lexeme[MAX_LEXEME_SIZE];
typedef char Text[MAX_TEXT_SIZE];

enum type
{
	TYPE_CLASS = 1,				
	TYPE_MAIN = 2,				
	TYPE_DO = 3,
	TYPE_WHILE = 4,
	TYPE_SHORT = 5,
	TYPE_LONG = 6,
	TYPE_BOOL = 7,
	TYPE_TRUE = 8,
	TYPE_FALSE = 9,
	TYPE_RETURN = 10,
	TYPE_MAIN_FUNC = 11,

	TYPE_IDENTIFIER = 12,

	TYPE_CONST_DECIMAL = 13,
	TYPE_CONST_HEX = 14,

	TYPE_COMMA = 15,
	TYPE_SEMICOLON = 16,
	TYPE_OPEN_PARENTHESES = 17,
	TYPE_CLOSED_PARENTHESES = 18,
	TYPE_OPEN_BRACES = 19,
	TYPE_CLOSED_BRACES = 20,

	TYPE_LESS = 21,
	TYPE_LESS_EQUAL = 22,
	TYPE_MORE = 23,
	TYPE_MORE_EQUAL = 24,
	TYPE_EQUAL = 25,
	TYPE_NOT_EQUAL = 26,
	TYPE_PLUS = 27,
	TYPE_MINUS = 28,
	TYPE_MULTIPLICATION = 29,
	TYPE_DIVISION = 30,
	TYPE_SAVE = 31,

	TYPE_LOG_OR = 32,
	TYPE_LOG_AND = 33,
	TYPE_EXC_OR = 34,
	TYPE_DIV_REM = 35,
	TYPE_LOG_NOT = 36,

	TYPE_ERROR = 37,
	TYPE_END = 38
};

#endif //ANALYZATOR_DEFS_H